version: "3.8"
services:
  node:
    container_name: portfolio_node
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    working_dir: /portfolio
    entrypoint: tail -f /dev/null
    volumes:
      - ./:/portfolio
    ports:
      - "9000:9000"